### ISSUE TITLE
Better docs for overwriting base vars

### ISSUE THREAD

**Issue by DaniG2k** [twbs/bootstrap-rubygem#106]
Hello all,

I'm wondering how to override the base Bootstrap variables once I've installed this gem into my Rails app. The docs mention how to do so if I am using Compass, but I am not. I've simply included the gem and required it into my assets.

How can I override the variables otherwise?

Thanks

**Comment by cyrilsuzat** [comment]
To customize your variables, you can create a file with the variables you want to modify, and then import it before Bootstrap :

```scss
// assets/stylesheets/_variables.scss
$colors: (
  primary: #c00,
  my_color: #663
);

$enable-rounded: false;
$body-bg: #ccc;
```

```scss
// assets/stylesheets/application.scss
@import "variables";
@import "bootstrap";

h1 {
  color: color("my_color");
}
```

You will find more info on customizing variables [here](https://getbootstrap.com/docs/4.0/getting-started/options/#customizing-variables)
