### ISSUE TITLE
No glyphicons

### ISSUE THREAD

**Issue by JuliaUsanova** [twbs/bootstrap-rubygem#142]
There is no glyphicons and no instruction how to load it, but normally bootstrap goes with this set of fonts too

**Comment by Johann-S** [comment]
There were glyphicons in BS v3 but not in v4, see: https://getbootstrap.com/docs/4.0/migration/#components

**Comment by JuliaUsanova** [comment]
@Johann-S, Thank you a lot!

**Comment by berkes** [comment]
Not sure if this is related, but I found that in my case, glyphicons did not use the `asset_url`. 

So, it has this CSS:

````CSS
@font-face {
  font-family: "Glyphicons Halflings";
  src: url("/assets/bootstrap/glyphicons-halflings-regular.eot");
  /*..all other URLS, for ttf, woff etc similarly structured..*/ 
}
````
And not:
````CSS
@font-face {
  font-family: 'Glyphicons Halflings FAIL';
  src: url(/assets/bootstrap/glyphicons-halflings-regular-13634da87d9e23f8c3ed9108ce1724d183a39ad072e73e1b3d8cbf646d2d0407.eot);
   /*..all other URLS, for ttf, woff etc similarly structured..*/ 
}
````

The hash is embedded by the asset precompiler in Rails/sprockets. The actual files are the ones with the hash; so the last piece of CSS loads the fonts, the first generates `404`s

Maybe this is another issue, maybe it is related, or maybe this is what causes this for other people running into this.
